//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cavity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cavity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not an abstract base class..
        /// </summary>
        internal static string AbstractBaseClassTestException_Message {
            get {
                return ResourceManager.GetString("AbstractBaseClassTestException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not derived from {1}..
        /// </summary>
        internal static string BaseClassTestException_Message {
            get {
                return ResourceManager.GetString("BaseClassTestException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a concrete class..
        /// </summary>
        internal static string ConcreteClassTestException_Message {
            get {
                return ResourceManager.GetString("ConcreteClassTestException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with {1}..
        /// </summary>
        internal static string DecorationTestException_MissingMessage {
            get {
                return ResourceManager.GetString("DecorationTestException_MissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is unexpectedly decorated with at least one attribute..
        /// </summary>
        internal static string DecorationTestException_UnexpectedMessage {
            get {
                return ResourceManager.GetString("DecorationTestException_UnexpectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have a default constructor..
        /// </summary>
        internal static string DefaultConstructorTestException_Message {
            get {
                return ResourceManager.GetString("DefaultConstructorTestException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not implement {1}..
        /// </summary>
        internal static string ImplementationTestException_NoneMessage {
            get {
                return ResourceManager.GetString("ImplementationTestException_NoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unexpectedly implements at least one interface..
        /// </summary>
        internal static string ImplementationTestException_UnexpectedMessage {
            get {
                return ResourceManager.GetString("ImplementationTestException_UnexpectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not an interface..
        /// </summary>
        internal static string InterfaceTestException_Message {
            get {
                return ResourceManager.GetString("InterfaceTestException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the XmlArray(...) method instead of this generic method..
        /// </summary>
        internal static string PropertyExpectations_IsDecoratedWithXmlArray {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the XmlAttribute(...) method instead of this generic method..
        /// </summary>
        internal static string PropertyExpectations_IsDecoratedWithXmlAttribute {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the XmlElement(...) method instead of this generic method..
        /// </summary>
        internal static string PropertyExpectations_IsDecoratedWithXmlElement {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the XmlIgnore() method instead of this generic method..
        /// </summary>
        internal static string PropertyExpectations_IsDecoratedWithXmlIgnore {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the XmlNamespaceDeclarationsAttribute() method instead of this generic method..
        /// </summary>
        internal static string PropertyExpectations_IsDecoratedWithXmlNamespaceDeclarations {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlNamespaceDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the XmlText() method instead of this generic method..
        /// </summary>
        internal static string PropertyExpectations_IsDecoratedWithXmlText {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} did not equal the expected value..
        /// </summary>
        internal static string PropertyGetterTestException_Message {
            get {
                return ResourceManager.GetString("PropertyGetterTestException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} did not equal the expected value..
        /// </summary>
        internal static string PropertyGetterTestOfTException_Message {
            get {
                return ResourceManager.GetString("PropertyGetterTestOfTException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} did not throw the expected {2}..
        /// </summary>
        internal static string PropertySetterTestException_Message {
            get {
                return ResourceManager.GetString("PropertySetterTestException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(...) should return a record with the correct {1}..
        /// </summary>
        internal static string Repository_ExpectCorrectRecordValue_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ExpectCorrectRecordValue_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(...) should return the correct {1}..
        /// </summary>
        internal static string Repository_ExpectCorrectValue_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ExpectCorrectValue_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(...) should throw a RepositoryException when the record does not specify {1}..
        /// </summary>
        internal static string Repository_ExpectExceptionWhenRecordIncomplete_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ExpectExceptionWhenRecordIncomplete_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(...) should throw a RepositoryException when a record with the key does not exist..
        /// </summary>
        internal static string Repository_ExpectExceptionWhenRecordKeyNotFound_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ExpectExceptionWhenRecordKeyNotFound_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(...) should throw an ArgumentNullException when a record is not specified..
        /// </summary>
        internal static string Repository_ExpectExceptionWhenRecordNull_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ExpectExceptionWhenRecordNull_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(...) should throw an ArgumentNullException when a URN is not specified..
        /// </summary>
        internal static string Repository_ExpectExceptionWhenUrnNull_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ExpectExceptionWhenUrnNull_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(...) should return null when the {1} is not found..
        /// </summary>
        internal static string Repository_ExpectNullWhenRecordNotFound_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ExpectNullWhenRecordNotFound_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(...) should return a {1}..
        /// </summary>
        internal static string Repository_ExpectResult_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ExpectResult_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(...) should return true when an existing record is {1}..
        /// </summary>
        internal static string Repository_ExpectTrueWhenExistingRecord_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ExpectTrueWhenExistingRecord_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(...) should return {1} when the record does not exist..
        /// </summary>
        internal static string Repository_ExpectWhenDoesNotExist_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ExpectWhenDoesNotExist_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(...) should return {1} when the record exists..
        /// </summary>
        internal static string Repository_ExpectWhenExists_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ExpectWhenExists_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert(...) should throw a RepositoryException when a record with the key already exists..
        /// </summary>
        internal static string Repository_Insert_RecordKeyExists_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_Insert_RecordKeyExists_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert(...) should throw a RepositoryException when a record with the URN already exists..
        /// </summary>
        internal static string Repository_Insert_RecordUrnExists_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_Insert_RecordUrnExists_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert(...) should set the key of the returned record..
        /// </summary>
        internal static string Repository_Insert_ReturnsIncorrectKey_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_Insert_ReturnsIncorrectKey_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert(...) should set the created date of the returned record..
        /// </summary>
        internal static string Repository_Insert_ReturnsWithoutCreated_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_Insert_ReturnsWithoutCreated_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert(...) should set the modified date of the returned record..
        /// </summary>
        internal static string Repository_Insert_ReturnsWithoutModified_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_Insert_ReturnsWithoutModified_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match(...) should return true when a matching record exists..
        /// </summary>
        internal static string Repository_Match_ReturnsFalse_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_Match_ReturnsFalse_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match(...) should return false when no matching record exists..
        /// </summary>
        internal static string Repository_Match_ReturnsTrue_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_Match_ReturnsTrue_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifiedSince(...) should return true when the record has been modified since the specified date..
        /// </summary>
        internal static string Repository_ModifiedSince_ReturnsFalse_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ModifiedSince_ReturnsFalse_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifiedSince(...) should return false when the record has not been modified since the specified date..
        /// </summary>
        internal static string Repository_ModifiedSince_ReturnsTrue_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_ModifiedSince_ReturnsTrue_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception was encountered..
        /// </summary>
        internal static string Repository_UnexpectedException_UnitTestExceptionMessage {
            get {
                return ResourceManager.GetString("Repository_UnexpectedException_UnitTestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unexpectedly is a sealed class..
        /// </summary>
        internal static string SealedClassTestException_SealedMessage {
            get {
                return ResourceManager.GetString("SealedClassTestException_SealedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a sealed class..
        /// </summary>
        internal static string SealedClassTestException_UnsealedMessage {
            get {
                return ResourceManager.GetString("SealedClassTestException_UnsealedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the Serializable() method instead of this generic method..
        /// </summary>
        internal static string TypeExpectations_IsDecoratedWithSerializable {
            get {
                return ResourceManager.GetString("TypeExpectations_IsDecoratedWithSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the XmlRoot(...) method instead of this generic method..
        /// </summary>
        internal static string TypeExpectations_IsDecoratedWithXmlRoot {
            get {
                return ResourceManager.GetString("TypeExpectations_IsDecoratedWithXmlRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An interface type must be specified..
        /// </summary>
        internal static string TypeExpectationsException_InterfaceMessage {
            get {
                return ResourceManager.GetString("TypeExpectationsException_InterfaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a value type..
        /// </summary>
        internal static string ValueTypeTestException_Message {
            get {
                return ResourceManager.GetString("ValueTypeTestException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlArray]..
        /// </summary>
        internal static string XmlArrayDecorationTestException_Message1 {
            get {
                return ResourceManager.GetString("XmlArrayDecorationTestException_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlArray(\&quot;{1}\&quot;)]..
        /// </summary>
        internal static string XmlArrayDecorationTestException_Message2 {
            get {
                return ResourceManager.GetString("XmlArrayDecorationTestException_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlArrayItem]..
        /// </summary>
        internal static string XmlArrayDecorationTestException_Message3 {
            get {
                return ResourceManager.GetString("XmlArrayDecorationTestException_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlArrayItem(\&quot;{1}\&quot;)]..
        /// </summary>
        internal static string XmlArrayDecorationTestException_Message4 {
            get {
                return ResourceManager.GetString("XmlArrayDecorationTestException_Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlAttribute]..
        /// </summary>
        internal static string XmlAttributeDecorationTestException_Message1 {
            get {
                return ResourceManager.GetString("XmlAttributeDecorationTestException_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlAttribute(\&quot;{1}\&quot;)]..
        /// </summary>
        internal static string XmlAttributeDecorationTestException_Message2 {
            get {
                return ResourceManager.GetString("XmlAttributeDecorationTestException_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlAttribute(\&quot;{1}\&quot;, \&quot;{2}\&quot;)]..
        /// </summary>
        internal static string XmlAttributeDecorationTestException_Message3 {
            get {
                return ResourceManager.GetString("XmlAttributeDecorationTestException_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlElement]..
        /// </summary>
        internal static string XmlElementDecorationTestException_Message1 {
            get {
                return ResourceManager.GetString("XmlElementDecorationTestException_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlElement(\&quot;{1}\&quot;)]..
        /// </summary>
        internal static string XmlElementDecorationTestException_Message2 {
            get {
                return ResourceManager.GetString("XmlElementDecorationTestException_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlElement(\&quot;{1}\&quot;, \&quot;{2}\&quot;)]..
        /// </summary>
        internal static string XmlElementDecorationTestException_Message3 {
            get {
                return ResourceManager.GetString("XmlElementDecorationTestException_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlIgnore]..
        /// </summary>
        internal static string XmlIgnoreDecorationTestException_Message {
            get {
                return ResourceManager.GetString("XmlIgnoreDecorationTestException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlNamespaceDeclarations]..
        /// </summary>
        internal static string XmlNamespaceDeclarationsDecorationTestException_Message {
            get {
                return ResourceManager.GetString("XmlNamespaceDeclarationsDecorationTestException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlRoot(\&quot;{1}\&quot;)]..
        /// </summary>
        internal static string XmlRootDecorationTestException_NameMessage {
            get {
                return ResourceManager.GetString("XmlRootDecorationTestException_NameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlRoot(\&quot;{1}\&quot;, \&quot;{2}\&quot;)]..
        /// </summary>
        internal static string XmlRootDecorationTestException_NamespaceMessage {
            get {
                return ResourceManager.GetString("XmlRootDecorationTestException_NamespaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlRoot]..
        /// </summary>
        internal static string XmlRootDecorationTestException_UndecoratedMessage {
            get {
                return ResourceManager.GetString("XmlRootDecorationTestException_UndecoratedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with [XmlText]..
        /// </summary>
        internal static string XmlTextDecorationTestException_Message {
            get {
                return ResourceManager.GetString("XmlTextDecorationTestException_Message", resourceCulture);
            }
        }
    }
}
